### ISSUE TITLE
No module named 'Supervised'

### ISSUE THREAD

**Issue by drdebivre** [nityansuman/lazypredict-nightly#1]
I just installed lazypredict-nightly 0.3.1 in a conda environment. 
However, the library cannot be loaded in python due to the error "No module named 'Supervised'

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
----> import lazypredict
----> C:/.../miniforge3/envs/lazy-predict/Lib/site-packages/lazypredict/__init__.py:2 from Supervised import LazyClassifier, LazyRegressor
ModuleNotFoundError: No module named 'Supervised'

**Comment by nityansuman** [comment]
Thanks for pointing out @drdebivre. This has been fixed. Please re-install or update the package to v0.3.2 ((https://pypi.org/project/lazypredict-nightly/)
